//
//  Entries.swift
//  Ledgit
//
//  Created by Marcos Ortiz on 4/8/18.
//  Copyright © 2018 Camden Developers. All rights reserved.
//

import Foundation

let sampleTripEntries: [NSDictionary] = [
    [
        "key": "000000001",
        "date": Date().toString(style: .full),
        "currency": LedgitCurrency.USD.code,
        "location": "Prague",
        "entryDescription": "Lokal Lunch",
        "category": "Food",
        "paidBy": "",
        "paymentType": PaymentType.cash.rawValue,
        "owningTrip": "ledgit1234567890",
        "cost": 12.99,
        "convertedCost": 12.99,
        "exchangeRate": 1.00,
        "homeCurrency": LedgitCurrency.USD.code,
    ],
    [
        "key": "000000002",
        "date": Date().toString(style: .full),
        "currency": LedgitCurrency.USD.code,
        "location": "Prague",
        "entryDescription": "Tram tickets",
        "category": "Transportation",
        "paidBy": "",
        "paymentType": PaymentType.cash.rawValue,
        "owningTrip": "ledgit1234567890",
        "cost": 1.04,
        "convertedCost": 1.04,
        "exchangeRate": 1.00,
        "homeCurrency": LedgitCurrency.USD.code,
    ],
    [
        "key": "000000003",
        "date": Date().toString(style: .full),
        "currency": LedgitCurrency.USD.code,
        "location": "Prague",
        "entryDescription": "Tvdelnik Desert",
        "category": "Food",
        "paidBy": "",
        "paymentType": PaymentType.cash.rawValue,
        "owningTrip": "ledgit1234567890",
        "cost": 3.65,
        "convertedCost": 3.65,
        "exchangeRate": 1.00,
        "homeCurrency": LedgitCurrency.USD.code,
    ],
    [
        "key": "000000004",
        "date": 1.days.ago.toString(style: .full),
        "currency": LedgitCurrency.USD.code,
        "location": "Vienna",
        "entryDescription": "Hostel Seven Vienna",
        "category": "Lodging",
        "paidBy": "",
        "paymentType": PaymentType.cash.rawValue,
        "owningTrip": "ledgit1234567890",
        "cost": 16.79,
        "convertedCost": 16.79,
        "exchangeRate": 1.00,
        "homeCurrency": LedgitCurrency.USD.code,
    ],
    [
        "key": "000000005",
        "date": 1.days.ago.toString(style: .full),
        "currency": LedgitCurrency.USD.code,
        "location": "Vienna",
        "entryDescription": "Bus Ticket",
        "category": "Transportation",
        "paidBy": "",
        "paymentType": PaymentType.cash.rawValue,
        "owningTrip": "ledgit1234567890",
        "cost": 2.24,
        "convertedCost": 2.24,
        "exchangeRate": 1.00,
        "homeCurrency": LedgitCurrency.USD.code,
    ],
    [
        "key": "000000006",
        "date": 1.days.ago.toString(style: .full),
        "currency": LedgitCurrency.USD.code,
        "location": "Vienna",
        "entryDescription": "Figlmuller",
        "category": "Transportation",
        "paidBy": "",
        "paymentType": PaymentType.cash.rawValue,
        "owningTrip": "ledgit1234567890",
        "cost": 16.57,
        "convertedCost": 16.57,
        "exchangeRate": 1.00,
        "homeCurrency": LedgitCurrency.USD.code,
    ],
    [
        "key": "000000007",
        "date": 2.days.ago.toString(style: .full),
        "currency": LedgitCurrency.USD.code,
        "location": "Budapest",
        "entryDescription": "Kazimir Bistro",
        "category": "Food",
        "paidBy": "",
        "paymentType": PaymentType.cash.rawValue,
        "owningTrip": "ledgit1234567890",
        "cost": "12.14",
        "convertedCost": 12.14,
        "exchangeRate": 1.00,
        "homeCurrency": LedgitCurrency.USD.code,
    ],
    [
        "key": "000000008",
        "date": 2.days.ago.toString(style: .full),
        "currency": LedgitCurrency.USD.code,
        "location": "Budapest",
        "entryDescription": "Hostel One Basilica",
        "category": "Lodging",
        "paidBy": "",
        "paymentType": PaymentType.cash.rawValue,
        "owningTrip": "ledgit1234567890",
        "cost": 14.49,
        "convertedCost": 14.49,
        "exchangeRate": 1.00,
        "homeCurrency": LedgitCurrency.USD.code,
    ],
    [
        "key": "000000009",
        "date": 2.days.ago.toString(style: .full),
        "currency": LedgitCurrency.USD.code,
        "location": "Budapest",
        "entryDescription": "Metro",
        "category": "Transportation",
        "paidBy": "",
        "paymentType": PaymentType.cash.rawValue,
        "owningTrip": "ledgit1234567890",
        "cost": 1.28,
        "convertedCost": 1.28,
        "exchangeRate": 1.00,
        "homeCurrency": LedgitCurrency.USD.code,
    ],
    [
        "key": "000000010",
        "date": 3.days.ago.toString(style: .full),
        "currency": LedgitCurrency.USD.code,
        "location": "Zagreb",
        "entryDescription": "Whole Wide World Hostel",
        "category": "Lodging",
        "paidBy": "",
        "paymentType": PaymentType.cash.rawValue,
        "owningTrip": "ledgit1234567890",
        "cost": 11.36,
        "convertedCost": 11.36,
        "exchangeRate": 1.00,
        "homeCurrency": LedgitCurrency.USD.code,
    ],
    [
        "key": "000000011",
        "date": 3.days.ago.toString(style: .full),
        "currency": LedgitCurrency.USD.code,
        "location": "Zagreb",
        "entryDescription": "Breakfast",
        "category": "Food",
        "paidBy": "",
        "paymentType": PaymentType.cash.rawValue,
        "owningTrip": "ledgit1234567890",
        "cost": 1.29,
        "convertedCost": 1.29,
        "exchangeRate": 1.00,
        "homeCurrency": LedgitCurrency.USD.code,
    ],
    [
        "key": "000000012",
        "date": 3.days.ago.toString(style: .full),
        "currency": LedgitCurrency.USD.code,
        "location": "Zagreb",
        "entryDescription": "Tour",
        "category": "Entertainment",
        "paidBy": "",
        "paymentType": PaymentType.cash.rawValue,
        "owningTrip": "ledgit1234567890",
        "cost": 5.31,
        "convertedCost": 5.31,
        "exchangeRate": 1.00,
        "homeCurrency": LedgitCurrency.USD.code,
    ],
    [
        "key": "000000013",
        "date": 4.days.ago.toString(style: .full),
        "currency": LedgitCurrency.USD.code,
        "location": "Barcelona",
        "entryDescription": "Hipstel Hostel",
        "category": "Lodging",
        "paidBy": "",
        "paymentType": PaymentType.cash.rawValue,
        "owningTrip": "ledgit1234567890",
        "cost": 27.20,
        "convertedCost": 27.20,
        "exchangeRate": 1.00,
        "homeCurrency": LedgitCurrency.USD.code,
    ],
    [
        "key": "000000014",
        "date": 4.days.ago.toString(style: .full),
        "currency": LedgitCurrency.USD.code,
        "location": "Barcelona",
        "entryDescription": "Breakfast",
        "category": "Food",
        "paidBy": "",
        "paymentType": PaymentType.cash.rawValue,
        "owningTrip": "ledgit1234567890",
        "cost": 5.31,
        "convertedCost": 5.31,
        "exchangeRate": 1.00,
        "homeCurrency": LedgitCurrency.USD.code,
    ],
    [
        "key": "000000015",
        "date": 4.days.ago.toString(style: .full),
        "currency": LedgitCurrency.USD.code,
        "location": "Barcelona",
        "entryDescription": "CocoVail",
        "category": "Food",
        "paidBy": "",
        "paymentType": PaymentType.cash.rawValue,
        "owningTrip": "ledgit1234567890",
        "cost": 8.57,
        "convertedCost": 8.57,
        "exchangeRate": 1.00,
        "homeCurrency": LedgitCurrency.USD.code,
    ],
    [
        "key": "000000016",
        "date": 5.days.ago.toString(style: .full),
        "currency": LedgitCurrency.USD.code,
        "location": "Rome",
        "entryDescription": "Hostel",
        "category": "Lodging",
        "paidBy": "",
        "paymentType": PaymentType.cash.rawValue,
        "owningTrip": "ledgit1234567890",
        "cost": 21.90,
        "convertedCost": 21.90,
        "exchangeRate": 1.00,
        "homeCurrency": LedgitCurrency.USD.code,
    ],
    [
        "key": "000000017",
        "date": 5.days.ago.toString(style: .full),
        "currency": LedgitCurrency.USD.code,
        "location": "Rome",
        "entryDescription": "Colosseum",
        "category": "Museums",
        "paidBy": "",
        "paymentType": PaymentType.cash.rawValue,
        "owningTrip": "ledgit1234567890",
        "cost": 20.81,
        "convertedCost": 20.81,
        "exchangeRate": 1.00,
        "homeCurrency": LedgitCurrency.USD.code,
    ],
    [
        "key": "000000018",
        "date": 5.days.ago.toString(style: .full),
        "currency": LedgitCurrency.USD.code,
        "location": "Rome",
        "entryDescription": "Angeletti Dinner",
        "category": "Food",
        "paidBy": "",
        "paymentType": PaymentType.cash.rawValue,
        "owningTrip": "ledgit1234567890",
        "cost": "13.79",
        "convertedCost": "13.79",
        "exchangeRate": "1.00",
        "homeCurrency": LedgitCurrency.USD.code,
    ],
    [
        "key": "000000019",
        "date": 6.days.ago.toString(style: .full),
        "currency": LedgitCurrency.USD.code,
        "location": "Florence",
        "entryDescription": "Hostel Santa Monica",
        "category": "Lodging",
        "paidBy": "",
        "paymentType": PaymentType.cash.rawValue,
        "owningTrip": "ledgit1234567890",
        "cost": 20.64,
        "convertedCost": 20.64,
        "exchangeRate": 1.00,
        "homeCurrency": LedgitCurrency.USD.code,
        ],
    [
        "key": "000000020",
        "date": 6.days.ago.toString(style: .full),
        "currency": LedgitCurrency.USD.code,
        "location": "Florence",
        "entryDescription": "Breakfast",
        "category": "Food",
        "paidBy": "",
        "paymentType": PaymentType.cash.rawValue,
        "owningTrip": "ledgit1234567890",
        "cost": 6.20,
        "convertedCost": 6.20,
        "exchangeRate": 1.00,
        "homeCurrency": LedgitCurrency.USD.code,
    ],
    [
        "key": "000000021",
        "date": 6.days.ago.toString(style: .full),
        "currency": LedgitCurrency.USD.code,
        "location": "Florence",
        "entryDescription": "Gardens",
        "category": "Entertainment",
        "paidBy": "",
        "paymentType": PaymentType.cash.rawValue,
        "owningTrip": "ledgit1234567890",
        "cost": 7.89,
        "convertedCost": 7.89,
        "exchangeRate": 1.00,
        "homeCurrency": LedgitCurrency.USD.code,
    ]
]
